import type { AppProps } from 'next/app'
// pages/_app.js
import { ChakraProvider } from '@chakra-ui/react'
import "../styles/globals.css";
import theme from '../theme'
import Head from 'next/head'
import '../styles/globals.css'


export default function App({ Component, pageProps }: AppProps) {
   return (
    <ChakraProvider theme={theme}>
      <Head>
        <title>Crypto Jr.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cryptojr-ico.png" />
      </Head>
      <Component {...pageProps} />
    </ChakraProvider>
  )
}