import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>CriptoJr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <div >
          <p>Quem somos?</p>
          <p>O que oferecemos?</p>
          <p>Faça parte da nossa equipe</p>
        </div>
      </main>
    </>
  );
}
