import Footer from "@/components/Footer";
import HomeSection from "@/components/Home";
import Navbar from "@/components/Navbar";
import Head from "next/head";
import About from "@/components/About";

export default function Home() {
  return (
    <>
      <Head>
        <title>Crypto Jr.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cryptojr-ico.png" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
      </Head>
      <main>
        <Navbar />

        <HomeSection />

        <div id="about-us">
          <About />
        </div>

        <Footer />
      </main>
    </>
  );
}
